version: "3"
services:

  crud-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: crud-web
    image: sca-client
    ports:
      - '8081:8081'
    depends_on:
      - crud-db
    environment:
    - PORT=8081
    - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
  
  crud-db:
    image: postgres:latest
    ports:
      - 5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-crud
         - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
         
 #SPRING_PROFILES_ACTIVE=test docker-compose up --build
