version: "3"
services:

  crud-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: crud-web
    image: sca-crud
    ports:
      - '8081:8081'
    depends_on:
      - crud-db
    environment:
    - PORT=8081
    - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
  
  crud-db:
    image: postgres:latest
    ports:
      - 5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-crud
         - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
         
#docker system prune //limpa o cache
#sudo SPRING_PROFILES_ACTIVE=hml TESTE=teste docker-compose up --build
#sudo docker ps -a (imagens já criadas)
#sudo docker build -t api-gateway-web  .
#sudo docker run -p 8080:8080 -d <nome da imagem>
#sudo docker stop <nome da imagem>
#sudo docker rm <nome da imagem>
#sudo docker ps (imagens ativas)