version: "3"
services:
  crud-db:
    image: postgres:latest
    ports:
      - 5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-crud
    networks:
      - sca-util-network
  crud-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: crud-web
    image: sca-crud
    ports:
      #As portas abaixo serão ignoradas pelo heroku, que obriga utilizar a 
      #porta que ele envia via variável de ambiente: $PORT
      #Essa porta deve ser configurada apenas no arquivo application.properties 
      #da aplicação, ou seja, em nenhum Dockerfile ou docker-compose
      - '8081:8081'
    depends_on:
      - crud-db
    environment:
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      - SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
    networks:
      - sca-util-network
networks:
    sca-util-network:
        driver: bridge 