version: "3"
services:
  crud-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: crud-web
    image: sca-crud
    ports:
      - '8081:8081'
    depends_on:
      - crud-db
    environment:
      - PORT=8081
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
    networks:
      - sca-util-network
  crud-db:
    image: postgres:latest
    ports:
      - 5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-crud
    networks:
      - sca-util-network
networks:
    sca-util-network:
        driver: bridge