#Travis yml do heroku
language: java
jdk:
  - oraclejdk11
cache:
  directories:
  - "$HOME/.cache"
script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn clean -Dgithub.repository.server.username=$GITHUB_REPOSITORY_SERVER_USERNAME -Dgithub.repository.server.password=$GITHUB_REPOSITORY_SERVER_PASSWORD -P github -DskipTests package
  - docker-compose build
install: skip
before_deploy:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - echo $HEROKU_PASSWORD | docker login --username $HEROKU_USERNAME --password-stdin registry.heroku.com
deploy:
  provider: script
  script:
    docker tag $APP_NAME $DOCKER_USERNAME/$APP_NAME:$TRAVIS_JOB_ID;
    docker tag $APP_NAME registry.heroku.com/$APP_NAME/web;
    docker push $DOCKER_USERNAME/$APP_NAME:$TRAVIS_JOB_ID;
    docker push registry.heroku.com/$APP_NAME/web;
    heroku container:release web --app $APP_NAME
  on:
    brach: master
notifications:
  email: false