insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (1, 'Escavadeira', 'VEICULO');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (2, 'Retroescavadeira','VEICULO');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (3, 'Caminhão','VEICULO');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (4, 'Trator','VEICULO');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (5, 'Carro','VEICULO');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (6, 'Britador de impacto','MAQUINA');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (7, 'Britador mandíbula','MAQUINA');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (8, 'Peneira vibratória','MAQUINA');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (9, 'Peneira desaguadora','MAQUINA');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (10,'Triturador','MAQUINA');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (11, 'Moinho de martelo','MAQUINA');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (12, 'Nivelador óptico','INSTRUMENTO_TOPOGRAFIA');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (13, 'Teodolito eletrônico','INSTRUMENTO_TOPOGRAFIA');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (14, 'Baliza topográfica','INSTRUMENTO_TOPOGRAFIA');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (15, 'Crackmeter','INSTRUMENTO_GEOTECNIA');
insert into tipo_descricao_insumo (id,descricao, tipo_insumo) values (16, 'Sismógrafo','INSTRUMENTO_GEOTECNIA');
	

insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (1,'Jcb','4CXECO', 1);  
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (2,'Hyundai','R220LC-9S',2);  
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (3,'Volkswagen','Constellation',3); 
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (4,'Komatsu','D575A',4); 
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (5,'Toyota','Hilux',5);  
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (6,'Ford','Ranger',5); 
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (7,'Hazemag','Hpi-H',6);  
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (8,'Metso', 'C130',7);  
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (9,'Mecmining do Brasil', 'MMB-3X1200',8);  
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (10,'Inbras','RS-24/01W',9);  
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (11,'Jiuchang','4PGS0809PT(Y)',10);    
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (12,'RG MAQ','RGM75C',11);  
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (13,'Xpex','AT-32',12);  
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (14,'Kolida','Kt-02',13);   
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (15,'Geogex','GX-BG33',14);
insert into tipo_marca_modelo (id, marca, modelo, tipo_descricao_insumo_id) values (16,'Geokon','4420',15);